name: "Hello World"

on:
  push:
    branches: ["main"]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World message"
        run: echo "Hello world from GitHub actions"

      - name: "Farewell"
        run: echo "See you later"